/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package life.cal;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.time.LocalDate;

/**
 *
 * @author User
 */
public class Register2 extends javax.swing.JFrame {
    
    private RegisterData data;
     
    /**
     * Creates new form Register2
     */
    public Register2() {
        initComponents();
        setLocationRelativeTo(null);
        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"ชาย","หญิง"}));
        btNext.setEnabled(false);              // กันเผลอกดบันทึก
    }

    // ใช้งานจริง: เรียกจากหน้าแรก
    public Register2(RegisterData data) {
        this();
        setRegisterData(data);
    }

    // สำหรับกรณีอยากส่ง email/password แยก
    public Register2(String email, String password) {
        this(new RegisterData(email, password));
    }

    public void setRegisterData(RegisterData data) {
        this.data = data;
        btNext.setEnabled(true);
    }

    private String mapGender(Object sel) {
        return "ชาย".equals(String.valueOf(sel)) ? "M" : "F";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfHight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfweight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tftarget = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Register");

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("เพศ");
        jPanel1.add(jLabel2);

        cbSex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexActionPerformed(evt);
            }
        });
        jPanel1.add(cbSex);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("อายุ");
        jPanel1.add(jLabel3);

        tfAge.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfAge);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("ส่วนสูง");
        jPanel1.add(jLabel4);

        tfHight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfHight);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("น้ำหนัก");
        jPanel1.add(jLabel5);

        tfweight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tfweight);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("น้ำหนักที่ต้องการ");
        jPanel1.add(jLabel6);

        tftarget.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tftarget);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("ปี");
        jPanel2.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ซม.");
        jPanel2.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("กก.");
        jPanel2.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("กก.");
        jPanel2.add(jLabel10);

        btNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btNext.setText("ลงทะเทียน");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btNext)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btNext)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        // TODO add your handling code here:
        try {
        // guard กันเปิดหน้านี้ตรง ๆ
        if (data == null || data.email == null ||
            !data.email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "โปรดเข้าหน้านี้ผ่านการสมัครขั้นที่ 1");
            return;
        }

        String gender = mapGender(cbSex.getSelectedItem());
        int age = Integer.parseInt(tfAge.getText().trim());
        double h = Double.parseDouble(tfHight.getText().trim());
        double w = Double.parseDouble(tfweight.getText().trim());
        String tgt = tftarget.getText().trim();
        Double goal = tgt.isEmpty() ? null : Double.parseDouble(tgt);

        if (age < 10 || age > 100) { JOptionPane.showMessageDialog(this, "อายุควร 10–100 ปี"); return; }
        if (h < 100 || h > 230)     { JOptionPane.showMessageDialog(this, "ส่วนสูง 100–230 ซม."); return; }
        if (w < 25 || w > 250)      { JOptionPane.showMessageDialog(this, "น้ำหนัก 25–250 กก."); return; }

        java.time.LocalDate birth = java.time.LocalDate.now().minusYears(age).withMonth(1).withDayOfMonth(1);

        data.gender        = gender;
        data.birthdate     = birth;
        data.heightCm      = h;
        data.weightKg      = w;
        data.goalWeightKg  = goal;
        data.activityLevel = "รอเต้ทำให้ครับณัฐคิดไม่ออก";
        data.name          = (data.email.contains("@")) ? data.email.substring(0, data.email.indexOf('@')) : "user";

        int id = new AuthService().registerFull(data);  // ← insert ลงตาราง User ที่นี่
        if (id > 0) {
            JOptionPane.showMessageDialog(this, "สร้างบัญชีสำเร็จ!");
            new HomeLogin().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ไม่สามารถสร้างบัญชีได้");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "อายุ/ส่วนสูง/น้ำหนัก/เป้าหมาย ต้องเป็นตัวเลข");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "ผิดพลาด: " + e.getMessage());
    
}

    
   
    }//GEN-LAST:event_btNextActionPerformed

    private void cbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbSexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNext;
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfHight;
    private javax.swing.JTextField tftarget;
    private javax.swing.JTextField tfweight;
    // End of variables declaration//GEN-END:variables
}
